export const statusData = [
  { text: "Intimations Patients", value: 50, color: "#E5BF59" },
  { text: "Successful claims", value: 50, color: "#00A82E" },
  { text: "Rejected Claims", value: 50, color: "#F93C23" },
  { text: "Reimbursements cases", value: 50, color: "#A06DD6" },
];
export const sipData = [
  { text: "Under Process", value: 10, color: "#A06dd6" },
  { text: "Query", value: 8, color: "#F93C23" },
  { text: "Initial Pending", value: 12, color: "#E5BF59" },
  { text: "Initial Received", value: 6, color: "#00A82E" },
  { text: "Discharge Under Review", value: 14, color: "#A06DD6" },
  { text: "Approval Pending", value: 9, color: "#F93C23" },
  { text: "Documents Missing", value: 11, color: "#E5BF59" },
  { text: "Payment Processing", value: 5, color: "#A06dd6" },
  { text: "Claim Finalized", value: 15, color: "#00A82E" },
  { text: "Reimbursement Pending", value: 7, color: "#F93C23" },
  { text: "Reimbursement Completed", value: 13, color: "#A06dd6" },
  { text: "Follow-up Required", value: 4, color: "#F93C23" },
];
export const caseData = [
  {
    ip: 14,
    age: 27,
    name: "Hitendra Kumar",
    mobileNo: "2233996769",
    serviceProvider: "Aditya Birla Health Insurance Company Ltd",
    hospital: "Fortis Noida",
    treatment: "Radiation Therapy",
  },
  {
    ip: 15,
    age: 35,
    name: "Rajesh Singh",
    mobileNo: "9988776655",
    serviceProvider: "ICICI Lombard",
    hospital: "Apollo Hospital Delhi",
    treatment: "Chemotherapy",
  },
  {
    ip: 16,
    age: 40,
    name: "Anita Sharma",
    mobileNo: "8877665544",
    serviceProvider: "Star Health",
    hospital: "Max Healthcare Gurgaon",
    treatment: "Dialysis",
  },
  {
    ip: 17,
    age: 50,
    name: "Manoj Verma",
    mobileNo: "7766554433",
    serviceProvider: "HDFC ERGO",
    hospital: "Medanta Medicity",
    treatment: "Knee Replacement",
  },
  {
    ip: 18,
    age: 29,
    name: "Suresh Patel",
    mobileNo: "6655443322",
    serviceProvider: "New India Assurance",
    hospital: "Manipal Hospital Bangalore",
    treatment: "Heart Surgery",
  },
  {
    ip: 19,
    age: 33,
    name: "Neha Gupta",
    mobileNo: "5544332211",
    serviceProvider: "Tata AIG",
    hospital: "Kokilaben Dhirubhai Ambani Hospital Mumbai",
    treatment: "Spine Surgery",
  },
];
